name: store_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Brett Morgan <brettmorgan@google.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.0
  logging: ^0.11.3+2
  shelf: ^0.7.5

dev_dependencies:
  pedantic: ^1.8.0
