name: store_server
description: A web server built using the shelf package.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.0
  logging: ^0.11.3+2
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  shrine_images:
    git:
      url: https://github.com/domesticmouse/material-components-flutter-codelabs-packages
      path: shrine_images/

dev_dependencies:
  grinder: ^0.8.3+1
  pedantic: ^1.8.0
  tuneup: ^0.3.6+1
